Consolidate github action workflows
Also update action version that are depreceated

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,7 @@
 # This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
 
-name: Gradle build and test
+name: Test and Build
 
 on:
   push:
@@ -18,70 +18,105 @@ permissions:
   checks: write
 
 jobs:
-  build:
+  unittests:
     name: Build and run unit tests
-
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           submodules: true
           fetch-depth: 0
       - name: Set up JDK 17
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
       - name: Build with Gradle
-        uses: gradle/gradle-build-action@v2
+        uses: gradle/gradle-build-action@v3
         with:
-          arguments: build
+          arguments: test
       - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v3
+        uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: '**/build/test-results/test/TEST-*.xml'
       - name: Upload build reports
         if: always()
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
-          name: build-reports
+          name: unitests-build-reports
           path: build/reports/
       - name: Upload package
         if: always()
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: test-package
           path: build/distributions/*.tar.gz
 
+  epicstests:
+    name: Run all unit tests reliant on EPICS install
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: true
+          fetch-depth: 0
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+      - name: Create Build Reports Folder
+        run: mkdir -p build/reports/tests
+      - name: Build and push
+        uses: docker/build-push-action@v5
+        with:
+          file: docker/Dockerfile
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+      - name: Run tests with docker compose
+        run: docker compose -f docker/docker-compose.epicsTests.yml run epicsarchiver-test
+        env:
+          DOCKER_DEFAULT_PLATFORM: linux/amd64
+          COMPOSE_DOCKER_CLI_BUILD: 1
+          DOCKER_BUILDKIT: 1
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/epicsTests/TEST-*.xml'
+      - name: Upload build reports
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: epicstests-build-reports
+          path: build/reports/
+
   build-custom-version:
-    needs: build
-    name: Build Slacdev site version
+    needs: [unittests, epicstests]
+    name: Build Slacdev and Default site version
     runs-on: ubuntu-latest
     strategy:
       matrix:
         siteid: ["slacdev", "default"]
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           submodules: true
           fetch-depth: 0
       - name: Set up JDK 17
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
       - name: Build with Gradle
-        uses: gradle/gradle-build-action@v2
+        uses: gradle/gradle-build-action@v3
         with:
           arguments: assemble
         env:
           ARCHAPPL_SITEID: ${{ matrix.siteid }}
       - name: Upload package
         if: always()
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: ${{ matrix.siteid }}-package
           path: build/distributions/*.tar.gz
