Add integration tests to ci

diff --git a/.github/workflows/test-and-build.yml b/.github/workflows/test-and-build.yml
--- a/.github/workflows/test-and-build.yml
+++ b/.github/workflows/test-and-build.yml
@@ -122,6 +122,45 @@ jobs:
           name: epicstests-build-reports
           path: build/reports/
 
+
+  integrationtests:
+    name: Run all unit tests reliant on web and possibly epics
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: true
+          fetch-depth: 0
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+      - name: Create Build Reports Folder
+        run: mkdir -p build/reports/tests
+      - name: Set up JDK 21
+        uses: actions/setup-java@v4
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
+      - name: Run tests with docker compose
+        run: docker compose -f docker/docker-compose.integrationTests.yml run epicsarchiver-test
+        env:
+          DOCKER_DEFAULT_PLATFORM: linux/amd64
+          COMPOSE_DOCKER_CLI_BUILD: 1
+          DOCKER_BUILDKIT: 1
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/integrationTests/TEST-*.xml'
+      - name: Upload build reports
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: integrationtests-build-reports
+          path: build/reports/
+
   build-custom-version:
     needs: [unittests, epicstests]
     name: Build Slacdev and Default site version
